modLoader="javafml"
loaderVersion="[36,)"
license="Apache-2.0"
[[mods]]
modId="elytrabounce"
version="${file.jarVersion}"
displayName="Elytra Bounce"
updateJSONURL="https://infernalstudios.org/api/mods/elytrabounce/forge"
logoFile="Elytra_Bounce_Banner.png"
authors="Infernal Studios"
description='''
Elytra Bounce lets you bounce against the ground with an elytra to build up and maintain momentum without firework rockets! 
Simply hold down the jump button while in flight, and you'll bounce!

Credits
LudoCrypt - Developer
Nekomaster1000 - Artist
'''
[[dependencies.elytrabounce]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.elytrabounce]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="CLIENT"
